import { useEffect, useMemo, useState } from "react";
import { RefreshCw, Search } from "lucide-react";
import Loading from "../components/Loading";
import { getRecoveryResults } from "../services/api";
import { ActionBadge, RiskBadge } from "./Dashboard";

function RecoveryResults() {
  const [rows, setRows] = useState([]);
  const [search, setSearch] = useState("");
  const [risk, setRisk] = useState("all");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const load = async () => {
    try {
      setLoading(true);
      setError("");
      const data = await getRecoveryResults();
      setRows(data.results || []);
    } catch (err) {
      setError(err.message || "Could not load recovery results.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
  }, []);

  const filtered = useMemo(() => {
    const term = search.toLowerCase().trim();

    return rows.filter((row) => {
      const matchesSearch =
        !term ||
        String(row.payment_id).toLowerCase().includes(term) ||
        String(row.failure_reason).toLowerCase().includes(term);

      const matchesRisk = risk === "all" || row.risk_level === risk;

      return matchesSearch && matchesRisk;
    });
  }, [rows, search, risk]);

  if (loading) return <Loading text="Loading recovery results..." />;

  if (error) {
    return (
      <div className="rounded-2xl border border-red-200 bg-red-50 p-6">
        <h2 className="font-semibold text-red-800">Results could not load</h2>
        <p className="mt-1 text-sm text-red-600">{error}</p>
        <button onClick={load} className="mt-4 rounded-xl bg-red-600 px-4 py-2 text-sm font-semibold text-white">
          Try again
        </button>
      </div>
    );
  }

  const money = (value) =>
    `₹${Number(value || 0).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;

  return (
    <div className="mx-auto max-w-[1600px]">
      <section className="rounded-2xl border border-slate-200 bg-white shadow-sm">
        <div className="border-b border-slate-100 p-5 sm:p-6">
          <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
            <div>
              <h2 className="text-xl font-bold text-slate-900">Recovery Results</h2>
              <p className="mt-1 text-sm text-slate-400">
                Review predictions generated by the recovery engine.
              </p>
            </div>

            <div className="flex flex-col gap-2 sm:flex-row">
              <div className="flex items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-3">
                <Search size={17} className="text-slate-400" />
                <input
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                  placeholder="Search payment or reason..."
                  className="w-full bg-transparent py-2.5 text-sm outline-none sm:w-64"
                />
              </div>

              <select
                value={risk}
                onChange={(e) => setRisk(e.target.value)}
                className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-medium text-slate-600 outline-none"
              >
                <option value="all">All risks</option>
                <option value="high">High</option>
                <option value="medium">Medium</option>
                <option value="low">Low</option>
              </select>

              <button
                onClick={load}
                className="flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-50"
              >
                <RefreshCw size={16} />
                Refresh
              </button>
            </div>
          </div>
        </div>

        <div className="border-b border-slate-100 bg-slate-50/70 px-5 py-3 text-xs text-slate-500">
          Showing <span className="font-semibold text-slate-800">{filtered.length}</span> of{" "}
          <span className="font-semibold text-slate-800">{rows.length}</span> results
        </div>

        <div className="overflow-x-auto">
          <table className="w-full min-w-[1100px] text-left text-sm">
            <thead className="bg-slate-50 text-[11px] uppercase tracking-wider text-slate-400">
              <tr>
                <th className="px-5 py-4">Payment</th>
                <th className="px-5 py-4">Amount</th>
                <th className="px-5 py-4">Probability</th>
                <th className="px-5 py-4">Risk</th>
                <th className="px-5 py-4">Action</th>
                <th className="px-5 py-4">Status</th>
                <th className="px-5 py-4">Failure Reason</th>
                <th className="px-5 py-4">Created</th>
              </tr>
            </thead>

            <tbody>
              {filtered.map((row) => (
                <tr key={row.result_id} className="border-t border-slate-100 hover:bg-slate-50/70">
                  <td className="px-5 py-4 font-semibold text-slate-800">{row.payment_id}</td>
                  <td className="px-5 py-4 text-slate-600">{money(row.amount)}</td>
                  <td className="px-5 py-4 font-semibold text-slate-700">
                    {(Number(row.recovery_probability) * 100).toFixed(1)}%
                  </td>
                  <td className="px-5 py-4"><RiskBadge risk={row.risk_level} /></td>
                  <td className="px-5 py-4"><ActionBadge action={row.recommended_action} /></td>
                  <td className="px-5 py-4">
                    <span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold capitalize text-slate-600">
                      {row.action_status}
                    </span>
                  </td>
                  <td className="px-5 py-4 capitalize text-slate-500">
                    {String(row.failure_reason || "").replaceAll("_", " ")}
                  </td>
                  <td className="px-5 py-4 whitespace-nowrap text-slate-400">
                    {row.created_at ? new Date(row.created_at).toLocaleString() : "-"}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {filtered.length === 0 && (
          <div className="p-12 text-center">
            <p className="font-semibold text-slate-700">No results found</p>
            <p className="mt-1 text-sm text-slate-400">Try changing your search or risk filter.</p>
          </div>
        )}
      </section>
    </div>
  );
}

export default RecoveryResults;